<a href="https://colab.research.google.com/github/zebsoftware/Machine-Learning/blob/main/Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [25]:
import pandas as pd
import numpy as np

In [26]:
country = ["pakistan",'india','nepal']
pd.Series(country)

0    pakistan
1       india
2       nepal
dtype: object

In [60]:
marks =[31,45,87,78]
pd.Series(marks)

0    31
1    45
2    87
3    78
dtype: int64

In [61]:
subjects = ['maths','english', 'physics','urdu']
pd.Series(marks,index=subjects)
print(marks)

maths      31
english    45
physics    87
urdu       78
dtype: int64

In [67]:
pd.Series(marks,index=subjects,name="my marks")
marks_series=pd.Series(marks,index=subjects,name="my marks")

In [42]:
marks_dict={
    'maths':31,
    'english':45,
    'physics':87,
    'urdu':78
}
marks_dict = pd.Series(marks_dict,name="ANWAR MARKS")

In [35]:
marks.size

4

In [38]:
marks.dtype

dtype('int64')

In [43]:
marks_dict.name

'ANWAR MARKS'

In [44]:
marks.is_unique

True

In [47]:
marks.index

Index(['maths', 'english', 'physics', 'urdu'], dtype='object')

In [69]:
marks_series.values

array([31, 45, 87, 78])